spring.application.name=HealthyTrack

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true

spring.datasource.url=jdbc:postgresql://localhost:5433/healthytrack
spring.datasource.username=admin
spring.datasource.password=admin1234
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8081

spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.time-zone=America/Guayaquil
spring.jackson.deserialization.fail-on-unknown-properties=false
spring.jackson.default-property-inclusion=non_null
spring.jackson.mapper.accept-case-insensitive-enums=true


